DROP TABLE la_llamita_bd.CAMBIO_ESTADO_INTERVENCION;
DROP TABLE la_llamita_bd.CAMBIO_ESTADO_TICKET;
DROP TABLE la_llamita_bd.CAPACITADO_PARA;
DROP TABLE la_llamita_bd.RECLASIFICACION;
DROP TABLE la_llamita_bd.INTERVENCION;
DROP TABLE la_llamita_bd.TICKET;
DROP TABLE la_llamita_bd.USUARIO;
DROP TABLE la_llamita_bd.EMPLEADO;
DROP TABLE la_llamita_bd.GRUPO_DE_RESOLUCION;
DROP TABLE la_llamita_bd.CLASIFICACION;
DROP TABLE la_llamita_bd.NUM_TICKET;

DELETE FROM la_llamita_bd.CAMBIO_ESTADO_INTERVENCION WHERE TRUE;
DELETE FROM la_llamita_bd.CAMBIO_ESTADO_TICKET WHERE TRUE;
DELETE FROM la_llamita_bd.RECLASIFICACION WHERE TRUE;
DELETE FROM la_llamita_bd.INTERVENCION WHERE TRUE;
DELETE FROM la_llamita_bd.TICKET WHERE TRUE;